name: Build generator

on: [ push ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    name: Build maven-central-publish-generator
    strategy:
      matrix:
        os:
          - windows-latest
          - macos-latest
    steps:
      - uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 8
      - run: chmod +x gradlew
      - run: ./gradlew build --scan
      - uses: actions/upload-artifact@v2
        if: "${{ matrix.os  == 'macos-latest' }}"
        with:
          name: macos-x64
          path: generator/build/bin/macosX64/releaseExecutable/maven-central-publish-generator.kexe
      - uses: actions/upload-artifact@v2
        if: "${{ matrix.os  == 'macos-latest' }}"
        with:
          name: linux-x64
          path: generator/build/bin/linuxX64/releaseExecutable/maven-central-publish-generator.kexe
      - uses: actions/upload-artifact@v2
        if: "${{ matrix.os  == 'windows-latest' }}"
        with:
          name: windows-x64
          path: generator/build/bin/mingwX64/releaseExecutable/maven-central-publish-generator.exe
